### ISSUE TITLE
No Wifi listed: Receiver not registered

### ISSUE THREAD

**Issue by Lem** [routerkeygen/routerkeygenAndroid#37]
**Device**: A001 (OnePlus One)
**Android**: 6.0.1
**CyanogenMod**: 13.0-20160325-NIGHTLY
**XPosed Framework**: 80
**XPrivacy**: 3.6.19(481) Pro

Switching from Android 5 to Android 6 with CyanogenMod I noticed that I don't get any results in the WiFi-List.
Building the latest git-source with Android-Studio and running in debug-mode I can see the following error:

```
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err: java.lang.IllegalArgumentException: Receiver not registered: org.exobel.routerkeygen.WifiScanReceiver@2b52811
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:781)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1205)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:582)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at org.exobel.routerkeygen.ui.NetworksListActivity.onStop(NetworksListActivity.java:285)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1279)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.Activity.performStop(Activity.java:6395)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.ActivityThread.handleSleeping(ActivityThread.java:3655)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.ActivityThread.-wrap19(ActivityThread.java)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1538)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.os.Looper.loop(Looper.java:148)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5461)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
03-27 14:40:19.609 5297-5297/org.exobel.routerkeygen W/System.err:     at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:117)
```

I don't know if this is caused by Xposed, will try without it on my next nighty-update of CM. All permissions for RouterKeygen are enabled in xprivacy and CM.
In the meantime can you maybe see somethin related to my error?

**Comment by TuxCoder** [comment]
@Lem 
I think you have to activate the  location permision.
Very strange android api.
https://developer.android.com/reference/android/net/wifi/WifiManager.html#getScanResults()

**Comment by Lem** [comment]
That shouldn't be the problem, these are granted, even in XPrivacy.
Somehow with 'Routerkeygen Yolosec' it works perfectly.

**Comment by ruiaraujo** [comment]
Fixed with latest release.
